### ISSUE TITLE
Code as C# version

### ISSUE THREAD

**Issue by FrankDoersam** [MrBatschner/Polladen#1]
Great work! I tried to convert the code to C# to run it on the Raspberry PI, but unfortunately it didn't work. Do you have the possibility to provide this in C# as a branch ?

**Comment by MrBatschner** [comment]
I have no experience in C#, so I will not be able to provide anything useful.

However, is the language that important? Have you tried the C implementation in the `polladen-in-c` branch? You could compile that into a small binary that you call from your C# environment as a subprocess…

**Comment by FrankDoersam** [comment]
Too bad, I would have preferred it in a solution. I have converted the code online, unfortunately only the action is not executed. I will test this with the c binary next.

**Comment by FrankDoersam** [comment]
Hello everyone,
i have tried to translate the code into c# but unfortunately it does not work like in python. i have output them to the console and they all look correct - can someone please help at this point.

Thank you very much!

best regards
frank




using System;
using System.Device.Gpio;
using System.Threading;

class Program
{
    // Timing constants
    static int[] DelaysCommandBit0 = { 320, 620 };
    static int[] DelaysCommandBit1 = { 620, 320 };
    static int[] DelaysSync = { 4500, 1400 };
    static int DelayBetweenSequence = 7400;
    static int DelayBetweenPresses = 20000;

    // Raspberry Pi GPIO settings
    static int RfTransmitPin = 17;

    // Command identifiers
    static int CommandShutterUp = 0x11;    // 0001 0001
    static int CommandShutterDown = 0x33;  // 0011 0011
    static int CommandShutterStop = 0x55;  // 0101 0101
    static int CommandLearn = 0xcc;        // 1100 1100

    static void Main(string[] args)
    {
        // GPIO setup
        GpioController gpioController = new GpioController(PinNumberingScheme.Logical);
        gpioController.OpenPin(RfTransmitPin, PinMode.Output);
        gpioController.Write(RfTransmitPin, PinValue.Low);

        // Command line arguments
        string command = args[0];
        int remoteId = 1336;
        int channel = 1;

        // Header calculation
        long header = 0x1fL << 32 | (remoteId & 0xffffL) << 16 | 0xffL << 12 | (channel & 0x0fL) << 8;

        // Execute command
        switch (command)
        {
            case "up":
                Up(header, gpioController);
                break;
            case "down":
                Down(header, gpioController);
                break;
            case "stop":
                Stop(header, gpioController);
                break;
            case "learn":
                Learn(header, gpioController);
                break;
            case "p2":
                P2(header, gpioController);
                break;
            case "pair":
                Pair(header, gpioController);
                break;
            case "change_direction":
                ChangeDirection(header, gpioController);
                break;
            default:
                Console.WriteLine("Invalid command");
                break;
        }

        // Cleanup GPIO
        gpioController.ClosePin(RfTransmitPin);

    }

    static void DelayMicroseconds(int microseconds)
    {
        double t2 = decimal.ToDouble(decimal.Divide(microseconds, 1000000));
        Thread.Sleep(TimeSpan.FromSeconds(t2));
    }

    static void SendBit(int[] delaySequence, GpioController gpioController)
    {
        gpioController.Write(RfTransmitPin, PinValue.High);
        DelayMicroseconds(delaySequence[0]);
        gpioController.Write(RfTransmitPin, PinValue.Low);
        DelayMicroseconds(delaySequence[1]);
    }

    static void SendSequence(long sequence, GpioController gpioController)
    {
        SendBit(DelaysSync, gpioController);

        for (int offset = 0; offset < 40; offset++)
        {
            long mask = 1L << (40 - 1 - offset);
            if ((sequence & mask) == 0)
                SendBit(DelaysCommandBit0, gpioController);
            else
                SendBit(DelaysCommandBit1, gpioController);
        }
    }

    static void SendCommand(long header, int command, GpioController gpioController, 
        int repeat = 6, bool invert = true)
    {
        long sequence = (long)(header + command);

        for (int x = 0; x < repeat; x++)
        {
            SendSequence(sequence, gpioController);
            DelayMicroseconds(DelayBetweenSequence);
        }

        if (invert)
        {
            sequence = (long)(header | (command & 0xf0) | ((command ^ 0xff) & 0x0f));
            for (int x = 0; x < repeat; x++)
            {
                SendSequence(sequence, gpioController);
                DelayMicroseconds(DelayBetweenSequence);
            }
        }
    }

    static void Up(long header, GpioController gpioController)
    {
        SendCommand(header, CommandShutterUp, gpioController);
    }

    static void Down(long header, GpioController gpioController)
    {
        SendCommand(header, CommandShutterDown, gpioController);
    }

    static void Stop(long header, GpioController gpioController)
    {
        SendCommand(header, CommandShutterStop, gpioController, 6, false);
    }

    static void Learn(long header, GpioController gpioController)
    {
        SendCommand(header, CommandLearn, gpioController, 6, false);
    }

    static void P2(long header, GpioController gpioController)
    {
        Learn(header, gpioController);
    }

    static void Pair(long header, GpioController gpioController)
    {
        Learn(header, gpioController);
        DelayMicroseconds(DelayBetweenPresses);
        Learn(header, gpioController);
        DelayMicroseconds(5 * DelayBetweenPresses);
        Up(header, gpioController);
    }

    static void ChangeDirection(long header, GpioController gpioController)
    {
        Learn(header, gpioController);
        DelayMicroseconds(DelayBetweenPresses);
        Learn(header, gpioController);
        DelayMicroseconds(5 * DelayBetweenPresses);
        Down(header, gpioController);
    }
}
